### ISSUE TITLE
请问，你有ROMNet和DecNet的代码么？

### ISSUE THREAD

**Issue by ymmmmmy** [Xiang3999/DGTD_LSTM#1]
最近在阅读这篇论文（A Comprehensive Deep Learning-Based Approach to Reduced Order Modeling of Nonlinear Time-Dependent Parametrized PDEs），然后看到作者的github中你留言了，想问问你有没有这篇论文重的ROMNet和DecNet的包，要过要是有的话，能不能麻烦您发送到我的邮箱：15926462694@163.com. 非常感谢。

**Comment by Xiang3999** [comment]
邮件回复你了，没有拿到这篇文章的源码。
